# Generated by Django 5.0.7 on 2024-07-29 16:27

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='beverages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='beverages/')),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('type', models.CharField(choices=[('MT', 'Masala tea'), ('GT', 'Ginger tea'), ('ET', 'Elaichi tea'), ('PT', 'Plain tea'), ('LT', 'Lemon tea'), ('GrT', 'Green tea'), ('CC', 'Cold coffee'), ('CP', 'Cappuccino'), ('VM', 'Virgin mojito'), ('MS', 'Masala soda'), ('LS', 'Lemon soda'),('FC','Filter coffee'),('OM', 'Oreo milkshake'),('BS', 'Butterscotch shake'),], max_length=3)),
            ],
        ),
    ]
