# Generated by Django 5.0.7 on 2024-07-29 20:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverages',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='beverages',
            name='image',
            field=models.ImageField(upload_to='softdrinks/'),
        ),
        migrations.AlterField(
            model_name='beverages',
            name='type',
            field=models.CharField(choices=[('MT', 'Masala tea'), ('GT', 'Ginger tea'), ('ET', 'Elaichi tea'), ('PT', 'Plain tea'), ('LT', 'Lemon tea'), ('GrT', 'Green tea'), ('CC', 'Cold coffee'), ('CP', 'Cappuccino'), ('FC', 'Filter coffee'), ('VM', 'Virgin mojito'), ('MS', 'Masala soda'), ('LS', 'Lemon soda'), ('OM', 'Oreo milkshake'), ('BS', 'Butterscotch shake')], max_length=3),
        ),
    ]
