# Generated by Django 5.0.7 on 2024-07-30 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishu', '0002_beverages_description_alter_beverages_image_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='beverages',
            name='prices',
            field=models.CharField(default='Re', max_length=100),
        ),
    ]
