# Generated by Django 5.1.7 on 2025-05-12 19:24

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishu', '0004_alter_beverages_prices_certificate_review_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='beverages',
            new_name='beverage',
        ),
        migrations.AlterField(
            model_name='certificate',
            name='valid_untill',
            field=models.DateTimeField(default=datetime.datetime(2027, 5, 14, 19, 24, 22, 877637, tzinfo=datetime.timezone.utc)),
        ),
    ]
