# Generated by Django 5.1.7 on 2025-05-15 12:01

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ishu', '0005_rename_beverages_beverage_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='certificate',
            name='valid_untill',
            field=models.DateTimeField(default=datetime.datetime(2027, 5, 17, 12, 1, 19, 8282, tzinfo=datetime.timezone.utc)),
        ),
    ]
